### ISSUE TITLE
Error on `init` function 

### ISSUE THREAD

**Issue by lizardwine** [jaedsonpys/vestory#2]
When i try to execute the `init `function an error it's raised  `ImportError: cannot import name 'Final'`

**Comment by jaedsonpys** [comment]
> When i try to execute the `init `function an error it's raised `ImportError: cannot import name 'Final'`

Hello, please make sure you are using Python version 3.8. The "Final" variable type imported from the "typing" module is used for constants, so it comes as standard Python library.
